apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-cfg
data:
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: admin
  # DB_VENDOR: postgres
  # DB_ADDR: 10.43.84.18
  # DB_PORT: "5432"
  # DB_DATABASE: keycloak
  # DB_USER: keycloak
  # DB_PASSWORD: keycloak
  # KEYCLOAK_LOG_LEVEL: DEBUG

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:16.1.1
          resources:
            limits:
              cpu: 1500m
              memory: 1536Mi
            requests:
              cpu: 250m
              memory: 768Mi
          envFrom:
            - configMapRef:
                name: keycloak-cfg
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          volumeMounts:
            - name: keycloak-data
              mountPath: /data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-lb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-igs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: keycloak.cluster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-svc
                port:
                  name: http
